/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'requirement' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'requirement' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };